-- 1

SELECT NOME, ANO
FROM FILMES

-- 2

SELECT NOME, ANO, DURACAO
FROM FILMES
ORDER BY ANO

-- 3

SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE NOME = 'De volta para o futuro'

-- 4

SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE ANO = 1997

-- 5

SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE ANO >= 2000

-- 6

SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE DURACAO > 100 AND DURACAO < 150
ORDER BY DURACAO

-- 7

SELECT ANO, COUNT(*) AS QUANTIDADE
FROM FILMES
GROUP BY ANO
ORDER BY QUANTIDADE DESC

-- 8

SELECT ID, PRIMEIRONOME, ULTIMONOME, GENERO
FROM ATORES
WHERE GENERO = 'M'

-- 9

SELECT ID, PRIMEIRONOME, ULTIMONOME, GENERO
FROM ATORES
WHERE GENERO = 'F'
ORDER BY PRIMEIRONOME

-- 10

SELECT F.NOME, G.GENERO
FROM FILMES F, GENEROS G, FILMESGENERO FM
WHERE F.ID = FM.IDFILME AND G.ID = FM.IDGENERO

-- 11

SELECT F.NOME, G.GENERO
FROM FILMES F, GENEROS G, FILMESGENERO FM
WHERE F.ID = FM.IDFILME AND G.ID = FM.IDGENERO AND G.GENERO = 'Mistério'

-- 12

SELECT F.NOME, A.PRIMEIRONOME, A.ULTIMONOME, EF.PAPEL
FROM FILMES F, ATORES A, ELENCOFILME EF
WHERE F.ID = EF.IDFILME AND A.ID = EF.IDATOR